schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        table_name:
          type: string
          description: "Shared Dynamo DB table name"
          default: myDynamoDbTable
          minLength: 3
          maxLength: 30
        stage_name:
          type: string
          description: "API Gateway stage name"
          default: stage
          minLength: 3
          maxLength: 30
        lambda_alias_name:
          type: string
          description: "Lambda Alias name"
          default: stage
